
name: Build and Test

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.15

    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Lint
      run: earthly +lint

    - name: Build
      run: |
        earthly +build-bookworm
        earthly +docker-bookworm

    - name: Test
      run: earthly +test
  
  release:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.15

    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Build and Push Image
      run: earthly --push +all --VERSION=${{ github.ref_name }}